### ISSUE TITLE
Problem with llvmlite version upon installation

### ISSUE THREAD

**Issue by jr-leary7** [sdomanskyi/DigitalCellSorter#2]
When attempting to install (Anaconda 3.7.4), I receive the message:

```
Collecting llvmlite>=0.30.0dev0 (from numba>=0.46->pynndescent>=0.3.3->DigitalCellSorter) 
```
And then later:

```bash
Found existing installation: llvmlite 0.29.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I checked the [release notes](https://llvmlite.readthedocs.io/en/latest/release-notes.html) for `llvmlite`, and the latest release is `v0.29.0`. The command I used to attempt to install `DigitalCellSorter` was `python3.7 -m pip install DigitalCellSorter`. Any help with regards to installation would be greatly appreciated.

**Comment by sdomanskyi** [comment]
This has to do with Anaconda being unable to upgrade its package llvmlite. The problem had been fixed in later versions of Anaconda. I recommend to export a list of installed packages. Then rename/remove your "anaconda" folder and install the latest version. Afterwards install DigitalCellSorter.
Note: trying to fix/upgrade existing installed version may be heavily time-consuming. Clean installation of anaconda is the fastest option.

**Comment by jr-leary7** [comment]
Once I reinstalled Anaconda and ran `conda update conda` and `conda update anaconda` everything went perfectly. Thank you!
